
ftp:
  host: 127.0.0.1
  username: test
  password: 123456
  port: 21

fileMonitor:
  remoteDir: /CMSFTPServer
  localDir: /var/alldata
  checkInterval: 5000
  monitorList:
    - fieldId:  "KULUN"
      daysBefore: 1
      deviceId: "FJ021"
      keyWordsList:
        - "test"
        - "demo"
camel:
  springboot:
    main-run-controller: true
server:
  port: 9080
