
ftp:
  host: 127.0.0.1
  username: test
  password: 123456
  port: 21
  encoding: gb2312
fileMonitor:
  remoteDir: /CMSFTPServer
  localDir: /var/alldata/data/CMSFTPServer
  checkInterval: 1800000
camel:
  springboot:
    main-run-controller: true
server:
  port: 9080
